In [2]:
import sklearn
import numpy as np
from sklearn.metrics import pairwise_distances

In [3]:
X = np.array([
    [-3.44, 1 ],
    [-6.48, 5],
    [0.93, -2],
    [0.2, 2],
    [-6.69, 13 ],
    [-5.85, 4],
    [3.0, 0],
    [-0.36, 0],
    [1.68, -3],
    [-0.45, -3]
    
])

np.set_printoptions(precision=2, linewidth=100, floatmode='fixed')
sklearn.metrics.pairwise_distances(X)

array([[ 0.00,  5.02,  5.30,  3.77, 12.43,  3.85,  6.52,  3.24,  6.50,  4.99],
       [ 5.02,  0.00, 10.19,  7.32,  8.00,  1.18, 10.72,  7.90, 11.43, 10.02],
       [ 5.30, 10.19,  0.00,  4.07, 16.82,  9.05,  2.88,  2.38,  1.25,  1.70],
       [ 3.77,  7.32,  4.07,  0.00, 12.98,  6.37,  3.44,  2.08,  5.21,  5.04],
       [12.43,  8.00, 16.82, 12.98,  0.00,  9.04, 16.21, 14.46, 18.06, 17.17],
       [ 3.85,  1.18,  9.05,  6.37,  9.04,  0.00,  9.71,  6.79, 10.28,  8.84],
       [ 6.52, 10.72,  2.88,  3.44, 16.21,  9.71,  0.00,  3.36,  3.28,  4.57],
       [ 3.24,  7.90,  2.38,  2.08, 14.46,  6.79,  3.36,  0.00,  3.63,  3.00],
       [ 6.50, 11.43,  1.25,  5.21, 18.06, 10.28,  3.28,  3.63,  0.00,  2.13],
       [ 4.99, 10.02,  1.70,  5.04, 17.17,  8.84,  4.57,  3.00,  2.13,  0.00]])

In [4]:
# 0 = star
# 1 = spade
y = np.array([
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    1,
    0
])

In [15]:
#a
from sklearn.neighbors import NearestNeighbors

#create a nearest neighbor classifier = 4 
NN = NearestNeighbors(n_neighbors=4)

#fit the data X to the classifier
NN.fit(X)

#extract the distances and neighbors from kneighbors function
#distances, neighbors = NN.kneighbors(X)
distances, neighbors = NN.kneighbors([X[1], X[7]])

#print(neighbors)
#print(distances)
#print the appropriate information
print(neighbors)

[[1 5 0 3]
 [7 3 2 9]]


In [16]:
#b
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import accuracy_score

loo = LeaveOneOut()  #leave one out classifier

errs = [] #errors list

#create leave one out CV split on X and iterate through all possible splits

#split the X data into test and train data based on indexes from split
for train_index, test_index in loo.split(X):
    #print(train_index, test_index)
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    
    #create a Nearest neighbor classifier = 1
    NN = KNeighborsClassifier(n_neighbors=1)  #defaults to radius 1, p=2

    #fit the classifier to the X data
    NN.fit(X_train, Y_train)

    #predict the label of the 'test' data
    pred_results = NN.predict(X_test)
    #print(pred_results)
    
    #compute the accuracy of the classification   #use predictor - against Y_Test
    acc_score = accuracy_score(pred_results, Y_test)
    #print(acc_score)
    
    #compute the error rate = 1-accuracy
    #append the error rate to a list
    errs.append(1-acc_score)
    
#once you complete iterating through all the different data find the mean of the error
np.mean(errs)


0.7

In [7]:
#c
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

errs2 = [] 

#create a kfold split = 3
kf = KFold(n_splits=3)
#iterate through all splits and find the train and test indexes
#split the data into train and text sets based on the indexes
for train_index, test_index in kf.split(X):
    #print(train_index, test_index)
    X2_train, X2_test = X[train_index], X[test_index]
    Y2_train, Y2_test = y[train_index], y[test_index]
    
    #create a nearest neighbor classifier = 3
    NN2 = KNeighborsClassifier(n_neighbors=3)
    
    #fit the data to the classifier
    NN2.fit(X2_train, Y2_train)
    
    #predict the label of the test data
    pred_results2 = NN2.predict(X2_test)
    
    #compute the accuracy of the prediction
    acc_score2 = accuracy_score(pred_results2, Y2_test)
    
    #compute the error rate = 1-accuracy
    #append the error rates to a list
    errs2.append(1-acc_score2)
#compute the mean of all error rates
np.mean(errs2)

0.5